Server - temporary dependency fix
Errors that prompted this:

```
src/controllers/pclass.controller.ts:168:65 - error TS2339: Property 'chainids' does not exist on type 'Where<PClass>'.
  Property 'chainids' does not exist on type 'AndClause<PClass>'.

168     if (filter && filter.where && (<Where<PClass>>filter.where).chainids) {
                                                                    ~~~~~~~~

src/controllers/pclass.controller.ts:169:48 - error TS2339: Property 'chainids' does not exist on type 'Where<AnyObject>'.
  Property 'chainids' does not exist on type 'Condition<AnyObject>'.

169         pclassi_queries.push({or: filter.where.chainids.inq.map((chainid: string) => {
```